### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus21/osveijer-assembly#1]
**Very well done Oliver!**

Your language concept is emusing. However, I'm not able to give input, nor see any output from your code execution.

Is this a case of "but it works on my machine", or did you forget to push everything?

Here are some notes on your code:

Intresting interpreter approach. Normally the error checking happens relative to the execution, not before execution. Your approach opens for a cleaner execution loop, but the trade-off is a complicated `check_syntax` and a longer runtime. `check_syntax` should be documented.

Also, since `rtype_inst`, `jtype_inst` and `stype_inst` are constant, they should be declared as global constants. Then `check_syntax` whould not have to take two arguments. Additionally, why does it exist three equal instructions `"steering"` and two `"radiomessage"`?
_Your code_:
```rust
let rtype_inst: [&str; 5] = ["understeer", "oversteer", "overtake", "sidebysideintot1","pitstop"];
let jtype_inst: [&str; 5] = ["divebomb"; 5];
let stype_inst: [&str; 5] = ["radiomessage","radiomessage","steering","steering","steering"];
```

My last confusion is that the source code in the provided file `fac.formula1` doesn't seem to match the language specifications.

Thanks for your hard work and good luck!

**Comment by Hellyhoken** [comment]
The reason for program seemingly not responding was that the file `fac.formula1` was simply misplaced. I might, on my machine, have ran `cargo run` in the `src` folder which would be why it worked for me.

Changed `check_syntax` to be ran during execution. Also added comments.

Changed instruction arrays to constants and removed the array for all instructions to eliminate need for duplicated instructions.

I do not understand the last confusion, to me everything in `fac.formula1` seems fine.

**Comment by violaso** [comment]
Thanks! That worked wonders!
